//! EXIF 标准标签
//! Feature: exif

use crate::TagId;

impl TagId {
    pub const MAKE: Self = Self("Make");
    pub const MODEL: Self = Self("Model");
    pub const DATE_TIME_ORIGINAL: Self = Self("DateTimeOriginal");
    pub const CREATE_DATE: Self = Self("CreateDate");
    pub const MODIFY_DATE: Self = Self("ModifyDate");
    pub const IMAGE_WIDTH: Self = Self("ImageWidth");
    pub const IMAGE_HEIGHT: Self = Self("ImageHeight");
    pub const ORIENTATION: Self = Self("Orientation");
    pub const X_RESOLUTION: Self = Self("XResolution");
    pub const Y_RESOLUTION: Self = Self("YResolution");
    pub const RESOLUTION_UNIT: Self = Self("ResolutionUnit");
    pub const SOFTWARE: Self = Self("Software");
    pub const COPYRIGHT: Self = Self("Copyright");
    pub const ARTIST: Self = Self("Artist");
    pub const IMAGE_DESCRIPTION: Self = Self("ImageDescription");
    pub const EXPOSURE_TIME: Self = Self("ExposureTime");
    pub const F_NUMBER: Self = Self("FNumber");
    pub const EXPOSURE_PROGRAM: Self = Self("ExposureProgram");
    pub const ISO: Self = Self("ISO");
    pub const SENSITIVITY_TYPE: Self = Self("SensitivityType");
    pub const RECOMMENDED_EXPOSURE_INDEX: Self = Self("RecommendedExposureIndex");
    pub const EXIF_VERSION: Self = Self("ExifVersion");
    pub const DATE_TIME_DIGITIZED: Self = Self("DateTimeDigitized");
    pub const COMPONENT_CONFIGURATION: Self = Self("ComponentConfiguration");
    pub const SHUTTER_SPEED_VALUE: Self = Self("ShutterSpeedValue");
    pub const APERTURE_VALUE: Self = Self("ApertureValue");
    pub const BRIGHTNESS_VALUE: Self = Self("BrightnessValue");
    pub const EXPOSURE_COMPENSATION: Self = Self("ExposureCompensation");
    pub const MAX_APERTURE_VALUE: Self = Self("MaxApertureValue");
    pub const SUBJECT_DISTANCE: Self = Self("SubjectDistance");
    pub const METERING_MODE: Self = Self("MeteringMode");
    pub const LIGHT_SOURCE: Self = Self("LightSource");
    pub const FLASH: Self = Self("Flash");
    pub const FOCAL_LENGTH: Self = Self("FocalLength");
    pub const pub const FOCAL_LENGTH_IN_35MM_FORMAT: Self = Self("FocalLengthIn35mmFormat");: Self = Self("");
    pub const FLASH_ENERGY: Self = Self("FlashEnergy");
    pub const SPATIAL_FREQUENCY_RESPONSE: Self = Self("SpatialFrequencyResponse");
    pub const FOCAL_PLANE_X_RESOLUTION: Self = Self("FocalPlaneXResolution");
    pub const FOCAL_PLANE_Y_RESOLUTION: Self = Self("FocalPlaneYResolution");
    pub const FOCAL_PLANE_RESOLUTION_UNIT: Self = Self("FocalPlaneResolutionUnit");
    pub const SUBJECT_LOCATION: Self = Self("SubjectLocation");
    pub const EXPOSURE_INDEX: Self = Self("ExposureIndex");
    pub const SENSING_METHOD: Self = Self("SensingMethod");
    pub const FILE_SOURCE: Self = Self("FileSource");
    pub const SCENE_TYPE: Self = Self("SceneType");
    pub const CFA_PATTERN: Self = Self("CFAPattern");
    pub const CUSTOM_RENDERED: Self = Self("CustomRendered");
    pub const EXPOSURE_MODE: Self = Self("ExposureMode");
    pub const WHITE_BALANCE: Self = Self("WhiteBalance");
    pub const DIGITAL_ZOOM_RATIO: Self = Self("DigitalZoomRatio");
    pub const pub const FOCAL_LENGTH_35EFL: Self = Self("FocalLength35efl");: Self = Self("");
    pub const SCENE_CAPTURE_TYPE: Self = Self("SceneCaptureType");
    pub const GAIN_CONTROL: Self = Self("GainControl");
    pub const CONTRAST: Self = Self("Contrast");
    pub const SATURATION: Self = Self("Saturation");
    pub const SHARPNESS: Self = Self("Sharpness");
    pub const DEVICE_SETTING_DESCRIPTION: Self = Self("DeviceSettingDescription");
    pub const SUBJECT_DISTANCE_RANGE: Self = Self("SubjectDistanceRange");
    pub const FILE_NAME: Self = Self("FileName");
    pub const DIRECTORY: Self = Self("Directory");
    pub const FILE_SIZE: Self = Self("FileSize");
    pub const FILE_MODIFY_DATE: Self = Self("FileModifyDate");
    pub const FILE_ACCESS_DATE: Self = Self("FileAccessDate");
    pub const FILE_INODE_CHANGE_DATE: Self = Self("FileInodeChangeDate");
    pub const FILE_PERMISSIONS: Self = Self("FilePermissions");
    pub const FILE_TYPE: Self = Self("FileType");
    pub const FILE_TYPE_EXTENSION: Self = Self("FileTypeExtension");
    pub const MIME_TYPE: Self = Self("MIMEType");
    pub const EXIF_BYTE_ORDER: Self = Self("ExifByteOrder");
    pub const CURRENT_ICC_PROFILE: Self = Self("CurrentICCProfile");
    pub const PROFILE_DATE_TIME: Self = Self("ProfileDateTime");
    pub const PROFILE_FILE_SIGNATURE: Self = Self("ProfileFileSignature");
    pub const PRIMARY_PLATFORM: Self = Self("PrimaryPlatform");
    pub const CMM_TYPE: Self = Self("CMMType");
    pub const PROFILE_VERSION: Self = Self("ProfileVersion");
    pub const PROFILE_CLASS: Self = Self("ProfileClass");
    pub const COLOR_SPACE_DATA: Self = Self("ColorSpaceData");
    pub const PROFILE_CONNECTION_SPACE: Self = Self("ProfileConnectionSpace");
    pub const PROFILE_CONNECTION_SPACE_ILLUMINANT: Self = Self("ProfileConnectionSpaceIlluminant");
    pub const ICC_PROFILE_CREATOR: Self = Self("ICCProfileCreator");
    pub const ICC_PROFILE_DESCRIPTION: Self = Self("ICCProfileDescription");
    pub const ICC_VIEWING_CONDITIONS_DESCRIPTION: Self = Self("ICCViewingConditionsDescription");
    pub const ICC_DEVICE_MODEL: Self = Self("ICCDeviceModel");
    pub const ICC_DEVICE_MANUFACTURER: Self = Self("ICCDeviceManufacturer");
    pub const IMAGE_SIZE: Self = Self("ImageSize");
    pub const MEGAPIXELS: Self = Self("Megapixels");
    pub const QUALITY: Self = Self("Quality");
    pub const BITS_PER_SAMPLE: Self = Self("BitsPerSample");
    pub const COLOR_COMPONENTS: Self = Self("ColorComponents");
    pub const Y_CB_CR_SUB_SAMPLING: Self = Self("YCbCrSubSampling");
    pub const Y_CB_CR_POSITIONING: Self = Self("YCbCrPositioning");
    pub const THUMBNAIL_IMAGE: Self = Self("ThumbnailImage");
    pub const THUMBNAIL_LENGTH: Self = Self("ThumbnailLength");
    pub const THUMBNAIL_OFFSET: Self = Self("ThumbnailOffset");
    pub const PREVIEW_IMAGE: Self = Self("PreviewImage");
    pub const PREVIEW_IMAGE_TYPE: Self = Self("PreviewImageType");
    pub const JPG_FROM_RAW: Self = Self("JpgFromRaw");
    pub const OTHER_IMAGE: Self = Self("OtherImage");
    pub const COLOR_SPACE: Self = Self("ColorSpace");
    pub const GAMMA: Self = Self("Gamma");
    pub const HYPERFOCAL_DISTANCE: Self = Self("HyperfocalDistance");
    pub const pub const SCALE_FACTOR_35EFL: Self = Self("ScaleFactor35efl");: Self = Self("");
    pub const CIRCLE_OF_CONFUSION: Self = Self("CircleOfConfusion");
    pub const FIELD_OF_VIEW: Self = Self("FieldOfView");
    pub const LENS_ID: Self = Self("LensID");
    pub const LENS_INFO: Self = Self("LensInfo");
    pub const LENS_SPEC: Self = Self("LensSpec");
    pub const LENS_MAKE: Self = Self("LensMake");
    pub const LENS_MODEL: Self = Self("LensModel");
    pub const LENS_SERIAL_NUMBER: Self = Self("LensSerialNumber");
    pub const pub const CANON_A_F_INFO2: Self = Self("AFInfo2");: Self = Self("");
    pub const pub const CANON_A_F_POINTS_IN_FOCUS1_D: Self = Self("AFPointsInFocus1D");: Self = Self("");
    pub const pub const CANON_A_F_POINTS_IN_FOCUS5_D: Self = Self("AFPointsInFocus5D");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION01: Self = Self("CameraColorCalibration01");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION02: Self = Self("CameraColorCalibration02");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION03: Self = Self("CameraColorCalibration03");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION04: Self = Self("CameraColorCalibration04");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION05: Self = Self("CameraColorCalibration05");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION06: Self = Self("CameraColorCalibration06");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION07: Self = Self("CameraColorCalibration07");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION08: Self = Self("CameraColorCalibration08");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION09: Self = Self("CameraColorCalibration09");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION10: Self = Self("CameraColorCalibration10");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION11: Self = Self("CameraColorCalibration11");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION12: Self = Self("CameraColorCalibration12");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION13: Self = Self("CameraColorCalibration13");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION14: Self = Self("CameraColorCalibration14");: Self = Self("");
    pub const pub const CANON_CAMERA_COLOR_CALIBRATION15: Self = Self("CameraColorCalibration15");: Self = Self("");
    pub const pub const CANON_COLOR_SPACE2: Self = Self("ColorSpace2");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_CUSTOM1: Self = Self("ColorTempCustom1");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_CUSTOM2: Self = Self("ColorTempCustom2");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_P_C1: Self = Self("ColorTempPC1");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_P_C2: Self = Self("ColorTempPC2");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_P_C3: Self = Self("ColorTempPC3");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN10: Self = Self("ColorTempUnknown10");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN11: Self = Self("ColorTempUnknown11");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN12: Self = Self("ColorTempUnknown12");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN13: Self = Self("ColorTempUnknown13");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN14: Self = Self("ColorTempUnknown14");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN15: Self = Self("ColorTempUnknown15");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN16: Self = Self("ColorTempUnknown16");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN17: Self = Self("ColorTempUnknown17");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN18: Self = Self("ColorTempUnknown18");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN19: Self = Self("ColorTempUnknown19");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN2: Self = Self("ColorTempUnknown2");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN20: Self = Self("ColorTempUnknown20");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN21: Self = Self("ColorTempUnknown21");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN22: Self = Self("ColorTempUnknown22");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN23: Self = Self("ColorTempUnknown23");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN24: Self = Self("ColorTempUnknown24");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN25: Self = Self("ColorTempUnknown25");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN26: Self = Self("ColorTempUnknown26");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN27: Self = Self("ColorTempUnknown27");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN28: Self = Self("ColorTempUnknown28");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN29: Self = Self("ColorTempUnknown29");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN3: Self = Self("ColorTempUnknown3");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN30: Self = Self("ColorTempUnknown30");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN31: Self = Self("ColorTempUnknown31");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN32: Self = Self("ColorTempUnknown32");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN33: Self = Self("ColorTempUnknown33");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN4: Self = Self("ColorTempUnknown4");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN5: Self = Self("ColorTempUnknown5");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN6: Self = Self("ColorTempUnknown6");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN7: Self = Self("ColorTempUnknown7");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN8: Self = Self("ColorTempUnknown8");: Self = Self("");
    pub const pub const CANON_COLOR_TEMP_UNKNOWN9: Self = Self("ColorTempUnknown9");: Self = Self("");
    pub const pub const CANON_COLOR_TONE_USER_DEF1: Self = Self("ColorToneUserDef1");: Self = Self("");
    pub const pub const CANON_COLOR_TONE_USER_DEF2: Self = Self("ColorToneUserDef2");: Self = Self("");
    pub const pub const CANON_COLOR_TONE_USER_DEF3: Self = Self("ColorToneUserDef3");: Self = Self("");
    pub const pub const CANON_CONTRAST_USER_DEF1: Self = Self("ContrastUserDef1");: Self = Self("");
    pub const pub const CANON_CONTRAST_USER_DEF2: Self = Self("ContrastUserDef2");: Self = Self("");
    pub const pub const CANON_CONTRAST_USER_DEF3: Self = Self("ContrastUserDef3");: Self = Self("");
    pub const pub const CANON_DIRECTORY_INDEX2: Self = Self("DirectoryIndex2");: Self = Self("");
    pub const pub const CANON_FACE1_POSITION: Self = Self("Face1Position");: Self = Self("");
    pub const pub const CANON_FACE2_POSITION: Self = Self("Face2Position");: Self = Self("");
    pub const pub const CANON_FACE3_POSITION: Self = Self("Face3Position");: Self = Self("");
    pub const pub const CANON_FACE4_POSITION: Self = Self("Face4Position");: Self = Self("");
    pub const pub const CANON_FACE5_POSITION: Self = Self("Face5Position");: Self = Self("");
    pub const pub const CANON_FACE6_POSITION: Self = Self("Face6Position");: Self = Self("");
    pub const pub const CANON_FACE7_POSITION: Self = Self("Face7Position");: Self = Self("");
    pub const pub const CANON_FACE8_POSITION: Self = Self("Face8Position");: Self = Self("");
    pub const pub const CANON_FACE9_POSITION: Self = Self("Face9Position");: Self = Self("");
    pub const pub const CANON_FILE_INDEX2: Self = Self("FileIndex2");: Self = Self("");
    pub const pub const CANON_FILTER_EFFECT_USER_DEF1: Self = Self("FilterEffectUserDef1");: Self = Self("");
    pub const pub const CANON_FILTER_EFFECT_USER_DEF2: Self = Self("FilterEffectUserDef2");: Self = Self("");
    pub const pub const CANON_FILTER_EFFECT_USER_DEF3: Self = Self("FilterEffectUserDef3");: Self = Self("");
    pub const pub const CANON_FOCUS_BRACKETING_CROP_DEPTH_COMPOSITE: Self =: Self = Self("");
    pub const pub const CANON_FOCUS_BRACKETING_EXPOSURE_SMOOTHING: Self =: Self = Self("");
    pub const pub const CANON_G_R_B_G_LEVELS_CUSTOM1: Self = Self("GRBGLevelsCustom1");: Self = Self("");
    pub const pub const CANON_G_R_B_G_LEVELS_CUSTOM2: Self = Self("GRBGLevelsCustom2");: Self = Self("");
    pub const pub const CANON_LONG_EXPOSURE_NOISE_REDUCTION2: Self = Self("LongExposureNoiseReduction2");: Self = Self("");
    pub const pub const CANON_MAX_FOCAL_LENGTH2: Self = Self("MaxFocalLength2");: Self = Self("");
    pub const pub const CANON_MEASURED_E_V2: Self = Self("MeasuredEV2");: Self = Self("");
    pub const pub const CANON_MEASURED_E_V3: Self = Self("MeasuredEV3");: Self = Self("");
    pub const pub const CANON_MIN_FOCAL_LENGTH2: Self = Self("MinFocalLength2");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_CUSTOM1: Self = Self("RGGBLevelsCustom1");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_CUSTOM2: Self = Self("RGGBLevelsCustom2");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_P_C1: Self = Self("RGGBLevelsPC1");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_P_C2: Self = Self("RGGBLevelsPC2");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_P_C3: Self = Self("RGGBLevelsPC3");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN10: Self = Self("RGGBLevelsUnknown10");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN11: Self = Self("RGGBLevelsUnknown11");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN12: Self = Self("RGGBLevelsUnknown12");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN13: Self = Self("RGGBLevelsUnknown13");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN14: Self = Self("RGGBLevelsUnknown14");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN15: Self = Self("RGGBLevelsUnknown15");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN16: Self = Self("RGGBLevelsUnknown16");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN17: Self = Self("RGGBLevelsUnknown17");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN18: Self = Self("RGGBLevelsUnknown18");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN19: Self = Self("RGGBLevelsUnknown19");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN2: Self = Self("RGGBLevelsUnknown2");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN20: Self = Self("RGGBLevelsUnknown20");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN21: Self = Self("RGGBLevelsUnknown21");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN22: Self = Self("RGGBLevelsUnknown22");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN23: Self = Self("RGGBLevelsUnknown23");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN24: Self = Self("RGGBLevelsUnknown24");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN25: Self = Self("RGGBLevelsUnknown25");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN26: Self = Self("RGGBLevelsUnknown26");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN27: Self = Self("RGGBLevelsUnknown27");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN28: Self = Self("RGGBLevelsUnknown28");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN29: Self = Self("RGGBLevelsUnknown29");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN3: Self = Self("RGGBLevelsUnknown3");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN30: Self = Self("RGGBLevelsUnknown30");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN31: Self = Self("RGGBLevelsUnknown31");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN32: Self = Self("RGGBLevelsUnknown32");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN33: Self = Self("RGGBLevelsUnknown33");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN4: Self = Self("RGGBLevelsUnknown4");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN5: Self = Self("RGGBLevelsUnknown5");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN6: Self = Self("RGGBLevelsUnknown6");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN7: Self = Self("RGGBLevelsUnknown7");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN8: Self = Self("RGGBLevelsUnknown8");: Self = Self("");
    pub const pub const CANON_R_G_G_B_LEVELS_UNKNOWN9: Self = Self("RGGBLevelsUnknown9");: Self = Self("");
    pub const pub const CANON_SATURATION_USER_DEF1: Self = Self("SaturationUserDef1");: Self = Self("");
    pub const pub const CANON_SATURATION_USER_DEF2: Self = Self("SaturationUserDef2");: Self = Self("");
    pub const pub const CANON_SATURATION_USER_DEF3: Self = Self("SaturationUserDef3");: Self = Self("");
    pub const pub const CANON_SELF_TIMER2: Self = Self("SelfTimer2");: Self = Self("");
    pub const pub const FUJI_COMPOSITE_IMAGE_COUNT1: Self = Self("CompositeImageCount1");: Self = Self("");
    pub const pub const FUJI_COMPOSITE_IMAGE_COUNT2: Self = Self("CompositeImageCount2");: Self = Self("");
    pub const pub const FUJI_FACE1_BIRTHDAY: Self = Self("Face1Birthday");: Self = Self("");
    pub const pub const FUJI_FACE1_CATEGORY: Self = Self("Face1Category");: Self = Self("");
    pub const pub const FUJI_FACE1_NAME: Self = Self("Face1Name");: Self = Self("");
    pub const pub const FUJI_FACE2_BIRTHDAY: Self = Self("Face2Birthday");: Self = Self("");
    pub const pub const FUJI_FACE2_CATEGORY: Self = Self("Face2Category");: Self = Self("");
    pub const pub const FUJI_FACE2_NAME: Self = Self("Face2Name");: Self = Self("");
    pub const pub const FUJI_FACE3_BIRTHDAY: Self = Self("Face3Birthday");: Self = Self("");
    pub const pub const FUJI_FACE3_CATEGORY: Self = Self("Face3Category");: Self = Self("");
    pub const pub const FUJI_FACE3_NAME: Self = Self("Face3Name");: Self = Self("");
    pub const pub const FUJI_FACE4_BIRTHDAY: Self = Self("Face4Birthday");: Self = Self("");
    pub const pub const FUJI_FACE4_CATEGORY: Self = Self("Face4Category");: Self = Self("");
    pub const pub const FUJI_FACE4_NAME: Self = Self("Face4Name");: Self = Self("");
    pub const pub const FUJI_FACE5_BIRTHDAY: Self = Self("Face5Birthday");: Self = Self("");
    pub const pub const FUJI_FACE5_CATEGORY: Self = Self("Face5Category");: Self = Self("");
    pub const pub const FUJI_FACE5_NAME: Self = Self("Face5Name");: Self = Self("");
    pub const pub const FUJI_FACE6_BIRTHDAY: Self = Self("Face6Birthday");: Self = Self("");
    pub const pub const FUJI_FACE6_CATEGORY: Self = Self("Face6Category");: Self = Self("");
    pub const pub const FUJI_FACE6_NAME: Self = Self("Face6Name");: Self = Self("");
    pub const pub const FUJI_FACE7_BIRTHDAY: Self = Self("Face7Birthday");: Self = Self("");
    pub const pub const FUJI_FACE7_CATEGORY: Self = Self("Face7Category");: Self = Self("");
    pub const pub const FUJI_FACE7_NAME: Self = Self("Face7Name");: Self = Self("");
    pub const pub const FUJI_FACE8_BIRTHDAY: Self = Self("Face8Birthday");: Self = Self("");
    pub const pub const FUJI_FACE8_CATEGORY: Self = Self("Face8Category");: Self = Self("");
    pub const pub const FUJI_FACE8_NAME: Self = Self("Face8Name");: Self = Self("");
    pub const pub const FUJI_FOCUS_MODE2: Self = Self("FocusMode2");: Self = Self("");
    pub const pub const FUJI_FUJI_MODEL2: Self = Self("FujiModel2");: Self = Self("");
    pub const pub const OLYMPUS_BLACK_LEVEL2: Self = Self("BlackLevel2");: Self = Self("");
    pub const pub const OLYMPUS_CAMERA_TYPE2: Self = Self("CameraType2");: Self = Self("");
    pub const pub const OLYMPUS_COLOR_MATRIX2: Self = Self("ColorMatrix2");: Self = Self("");
    pub const pub const OLYMPUS_DATA_DUMP2: Self = Self("DataDump2");: Self = Self("");
    pub const pub const OLYMPUS_DATE_TIME1: Self = Self("DateTime1");: Self = Self("");
    pub const pub const OLYMPUS_DATE_TIME2: Self = Self("DateTime2");: Self = Self("");
    pub const pub const OLYMPUS_DISTORTION_CORRECTION2: Self = Self("DistortionCorrection2");: Self = Self("");
    pub const pub const OLYMPUS_EXTERNAL_FLASH_A_E1: Self = Self("ExternalFlashAE1");: Self = Self("");
    pub const pub const OLYMPUS_EXTERNAL_FLASH_A_E2: Self = Self("ExternalFlashAE2");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL3000_K: Self = Self("GLevel3000K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL3300_K: Self = Self("GLevel3300K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL3600_K: Self = Self("GLevel3600K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL3900_K: Self = Self("GLevel3900K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL4000_K: Self = Self("GLevel4000K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL4300_K: Self = Self("GLevel4300K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL4500_K: Self = Self("GLevel4500K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL4800_K: Self = Self("GLevel4800K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL5300_K: Self = Self("GLevel5300K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL6000_K: Self = Self("GLevel6000K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL6600_K: Self = Self("GLevel6600K");: Self = Self("");
    pub const pub const OLYMPUS_G_LEVEL7500_K: Self = Self("GLevel7500K");: Self = Self("");
    pub const pub const OLYMPUS_IMAGE_QUALITY2: Self = Self("ImageQuality2");: Self = Self("");
    pub const pub const OLYMPUS_INDEX01: Self = Self("Index01");: Self = Self("");
    pub const pub const OLYMPUS_INDEX02: Self = Self("Index02");: Self = Self("");
    pub const pub const OLYMPUS_INDEX03: Self = Self("Index03");: Self = Self("");
    pub const pub const OLYMPUS_INDEX04: Self = Self("Index04");: Self = Self("");
    pub const pub const OLYMPUS_INDEX05: Self = Self("Index05");: Self = Self("");
    pub const pub const OLYMPUS_INDEX06: Self = Self("Index06");: Self = Self("");
    pub const pub const OLYMPUS_INDEX07: Self = Self("Index07");: Self = Self("");
    pub const pub const OLYMPUS_INDEX08: Self = Self("Index08");: Self = Self("");
    pub const pub const OLYMPUS_INDEX09: Self = Self("Index09");: Self = Self("");
    pub const pub const OLYMPUS_INDEX10: Self = Self("Index10");: Self = Self("");
    pub const pub const OLYMPUS_INDEX11: Self = Self("Index11");: Self = Self("");
    pub const pub const OLYMPUS_INDEX12: Self = Self("Index12");: Self = Self("");
    pub const pub const OLYMPUS_INDEX13: Self = Self("Index13");: Self = Self("");
    pub const pub const OLYMPUS_INDEX14: Self = Self("Index14");: Self = Self("");
    pub const pub const OLYMPUS_INDEX15: Self = Self("Index15");: Self = Self("");
    pub const pub const OLYMPUS_INDEX16: Self = Self("Index16");: Self = Self("");
    pub const pub const OLYMPUS_INTERNAL_FLASH_A_E1: Self = Self("InternalFlashAE1");: Self = Self("");
    pub const pub const OLYMPUS_INTERNAL_FLASH_A_E2: Self = Self("InternalFlashAE2");: Self = Self("");
    pub const pub const OLYMPUS_NOISE_REDUCTION2: Self = Self("NoiseReduction2");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS3000_K: Self = Self("RBLevels3000K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS3300_K: Self = Self("RBLevels3300K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS3600_K: Self = Self("RBLevels3600K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS3900_K: Self = Self("RBLevels3900K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS4000_K: Self = Self("RBLevels4000K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS4300_K: Self = Self("RBLevels4300K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS4500_K: Self = Self("RBLevels4500K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS4800_K: Self = Self("RBLevels4800K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS5300_K: Self = Self("RBLevels5300K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS6000_K: Self = Self("RBLevels6000K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS6600_K: Self = Self("RBLevels6600K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS7500_K: Self = Self("RBLevels7500K");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS_C_W_B1: Self = Self("RBLevelsCWB1");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS_C_W_B2: Self = Self("RBLevelsCWB2");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS_C_W_B3: Self = Self("RBLevelsCWB3");: Self = Self("");
    pub const pub const OLYMPUS_R_B_LEVELS_C_W_B4: Self = Self("RBLevelsCWB4");: Self = Self("");
    pub const pub const OLYMPUS_RAW_DEV_SATURATION3: Self = Self("RawDevSaturation3");: Self = Self("");
    pub const pub const OLYMPUS_SHADING_COMPENSATION2: Self = Self("ShadingCompensation2");: Self = Self("");
    pub const pub const OLYMPUS_UNKNOWN_BLOCK1: Self = Self("UnknownBlock1");: Self = Self("");
    pub const pub const OLYMPUS_UNKNOWN_BLOCK2: Self = Self("UnknownBlock2");: Self = Self("");
    pub const pub const OLYMPUS_UNKNOWN_BLOCK3: Self = Self("UnknownBlock3");: Self = Self("");
    pub const pub const OLYMPUS_UNKNOWN_BLOCK4: Self = Self("UnknownBlock4");: Self = Self("");
    pub const pub const OLYMPUS_WHITE_BALANCE2: Self = Self("WhiteBalance2");: Self = Self("");
    pub const pub const PANASONIC_CITY2: Self = Self("City2");: Self = Self("");
    pub const pub const PANASONIC_FACE1_POSITION: Self = Self("Face1Position");: Self = Self("");
    pub const pub const PANASONIC_FACE2_POSITION: Self = Self("Face2Position");: Self = Self("");
    pub const pub const PANASONIC_FACE3_POSITION: Self = Self("Face3Position");: Self = Self("");
    pub const pub const PANASONIC_FACE4_POSITION: Self = Self("Face4Position");: Self = Self("");
    pub const pub const PANASONIC_FACE5_POSITION: Self = Self("Face5Position");: Self = Self("");
    pub const pub const PANASONIC_L_U_T1_NAME: Self = Self("LUT1Name");: Self = Self("");
    pub const pub const PANASONIC_L_U_T1_OPACITY: Self = Self("LUT1Opacity");: Self = Self("");
    pub const pub const PANASONIC_L_U_T2_NAME: Self = Self("LUT2Name");: Self = Self("");
    pub const pub const PANASONIC_L_U_T2_OPACITY: Self = Self("LUT2Opacity");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE1_AGE: Self = Self("RecognizedFace1Age");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE1_NAME: Self = Self("RecognizedFace1Name");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE1_POSITION: Self = Self("RecognizedFace1Position");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE2_AGE: Self = Self("RecognizedFace2Age");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE2_NAME: Self = Self("RecognizedFace2Name");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE2_POSITION: Self = Self("RecognizedFace2Position");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE3_AGE: Self = Self("RecognizedFace3Age");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE3_NAME: Self = Self("RecognizedFace3Name");: Self = Self("");
    pub const pub const PANASONIC_RECOGNIZED_FACE3_POSITION: Self = Self("RecognizedFace3Position");: Self = Self("");
    pub const pub const PANASONIC_VERSION1: Self = Self("Version1");: Self = Self("");
    pub const pub const PANASONIC_VERSION2: Self = Self("Version2");: Self = Self("");
    pub const pub const CANON_SHARPNESS_USER_DEF1: Self = Self("SharpnessUserDef1");: Self = Self("");
    pub const pub const CANON_SHARPNESS_USER_DEF2: Self = Self("SharpnessUserDef2");: Self = Self("");
    pub const pub const CANON_SHARPNESS_USER_DEF3: Self = Self("SharpnessUserDef3");: Self = Self("");
    pub const pub const CANON_TIME_STAMP1: Self = Self("TimeStamp1");: Self = Self("");
    pub const pub const CANON_TONING_EFFECT_USER_DEF1: Self = Self("ToningEffectUserDef1");: Self = Self("");
    pub const pub const CANON_TONING_EFFECT_USER_DEF2: Self = Self("ToningEffectUserDef2");: Self = Self("");
    pub const pub const CANON_TONING_EFFECT_USER_DEF3: Self = Self("ToningEffectUserDef3");: Self = Self("");
    pub const pub const CANON_USER_DEF1_PICTURE_STYLE: Self = Self("UserDef1PictureStyle");: Self = Self("");
    pub const pub const CANON_USER_DEF2_PICTURE_STYLE: Self = Self("UserDef2PictureStyle");: Self = Self("");
    pub const pub const CANON_USER_DEF3_PICTURE_STYLE: Self = Self("UserDef3PictureStyle");: Self = Self("");
    pub const pub const NIKON_A_F_INFO2_VERSION: Self = Self("AFInfo2Version");: Self = Self("");
    pub const pub const NIKON_AUTO_CAPTURE_CRITERIA_MOTION_DIRECTION: Self =: Self = Self("");
    pub const pub const NIKON_AUTO_CAPTURE_CRITERIA_MOTION_SPEED: Self =: Self = Self("");
    pub const pub const NIKON_AUTO_CAPTURE_CRITERIA_SUBJECT_SIZE: Self =: Self = Self("");
    pub const pub const NIKON_AUTO_CAPTURE_CRITERIA_SUBJECT_TYPE: Self =: Self = Self("");
    pub const pub const NIKON_FACE10_POSITION: Self = Self("Face10Position");: Self = Self("");
    pub const pub const NIKON_FACE11_POSITION: Self = Self("Face11Position");: Self = Self("");
    pub const pub const NIKON_FACE12_POSITION: Self = Self("Face12Position");: Self = Self("");
    pub const pub const NIKON_FACE1_POSITION: Self = Self("Face1Position");: Self = Self("");
    pub const pub const NIKON_FACE2_POSITION: Self = Self("Face2Position");: Self = Self("");
    pub const pub const NIKON_FACE3_POSITION: Self = Self("Face3Position");: Self = Self("");
    pub const pub const NIKON_FACE4_POSITION: Self = Self("Face4Position");: Self = Self("");
    pub const pub const NIKON_FACE5_POSITION: Self = Self("Face5Position");: Self = Self("");
    pub const pub const NIKON_FACE6_POSITION: Self = Self("Face6Position");: Self = Self("");
    pub const pub const NIKON_FACE7_POSITION: Self = Self("Face7Position");: Self = Self("");
    pub const pub const NIKON_FACE8_POSITION: Self = Self("Face8Position");: Self = Self("");
    pub const pub const NIKON_FACE9_POSITION: Self = Self("Face9Position");: Self = Self("");
    pub const pub const NIKON_FIRMWARE_VERSION2: Self = Self("FirmwareVersion2");: Self = Self("");
    pub const pub const NIKON_FIRMWARE_VERSION3: Self = Self("FirmwareVersion3");: Self = Self("");
    pub const pub const NIKON_FIRMWARE_VERSION51: Self = Self("FirmwareVersion51");: Self = Self("");
    pub const pub const NIKON_FIRMWARE_VERSION56: Self = Self("FirmwareVersion56");: Self = Self("");
    pub const pub const NIKON_FLASH_EXPOSURE_COMP2: Self = Self("FlashExposureComp2");: Self = Self("");
    pub const pub const NIKON_FLASH_EXPOSURE_COMP3: Self = Self("FlashExposureComp3");: Self = Self("");
    pub const pub const NIKON_FLASH_EXPOSURE_COMP4: Self = Self("FlashExposureComp4");: Self = Self("");
    pub const pub const NIKON_H_D_R_LEVEL2: Self = Self("HDRLevel2");: Self = Self("");
    pub const pub const NIKON_I_F_D0: Self = Self("IFD0");: Self = Self("");
    pub const pub const NIKON_I_S_O2: Self = Self("ISO2");: Self = Self("");
    pub const pub const NIKON_I_S_O_EXPANSION2: Self = Self("ISOExpansion2");: Self = Self("");
    pub const pub const NIKON_LENS_FUNC1_BUTTON_PLAYBACK_MODE: Self = Self("LensFunc1ButtonPlaybackMode");: Self = Self("");
    pub const pub const NIKON_LENS_FUNC2_BUTTON_PLAYBACK_MODE: Self = Self("LensFunc2ButtonPlaybackMode");: Self = Self("");
    pub const pub const NIKON_MAKER_NOTES0X51: Self = Self("MakerNotes0x51");: Self = Self("");
    pub const pub const NIKON_MAKER_NOTES0X56: Self = Self("MakerNotes0x56");: Self = Self("");
    pub const pub const NIKON_MOVIE_I_S_O_AUTO_CONTROL_MANUAL_MODE: Self =: Self = Self("");
    pub const pub const NIKON_MOVIE_VIBRATION_REDUCTION_SAME_AS_PHOTO: Self =: Self = Self("");
    pub const pub const NIKON_MOVIE_VIGNETTE_CONTROL_SAME_AS_PHOTO: Self =: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS10_FOCAL_LENGTH: Self = Self("NonCPULens10FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS10_MAX_APERTURE: Self = Self("NonCPULens10MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS11_FOCAL_LENGTH: Self = Self("NonCPULens11FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS11_MAX_APERTURE: Self = Self("NonCPULens11MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS12_FOCAL_LENGTH: Self = Self("NonCPULens12FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS12_MAX_APERTURE: Self = Self("NonCPULens12MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS13_FOCAL_LENGTH: Self = Self("NonCPULens13FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS13_MAX_APERTURE: Self = Self("NonCPULens13MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS14_FOCAL_LENGTH: Self = Self("NonCPULens14FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS14_MAX_APERTURE: Self = Self("NonCPULens14MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS15_FOCAL_LENGTH: Self = Self("NonCPULens15FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS15_MAX_APERTURE: Self = Self("NonCPULens15MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS16_FOCAL_LENGTH: Self = Self("NonCPULens16FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS16_MAX_APERTURE: Self = Self("NonCPULens16MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS17_FOCAL_LENGTH: Self = Self("NonCPULens17FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS17_MAX_APERTURE: Self = Self("NonCPULens17MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS18_FOCAL_LENGTH: Self = Self("NonCPULens18FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS18_MAX_APERTURE: Self = Self("NonCPULens18MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS19_FOCAL_LENGTH: Self = Self("NonCPULens19FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS19_MAX_APERTURE: Self = Self("NonCPULens19MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS1_FOCAL_LENGTH: Self = Self("NonCPULens1FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS1_MAX_APERTURE: Self = Self("NonCPULens1MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS20_FOCAL_LENGTH: Self = Self("NonCPULens20FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS20_MAX_APERTURE: Self = Self("NonCPULens20MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS2_FOCAL_LENGTH: Self = Self("NonCPULens2FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS2_MAX_APERTURE: Self = Self("NonCPULens2MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS3_FOCAL_LENGTH: Self = Self("NonCPULens3FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS3_MAX_APERTURE: Self = Self("NonCPULens3MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS4_FOCAL_LENGTH: Self = Self("NonCPULens4FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS4_MAX_APERTURE: Self = Self("NonCPULens4MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS5_FOCAL_LENGTH: Self = Self("NonCPULens5FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS5_MAX_APERTURE: Self = Self("NonCPULens5MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS6_FOCAL_LENGTH: Self = Self("NonCPULens6FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS6_MAX_APERTURE: Self = Self("NonCPULens6MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS7_FOCAL_LENGTH: Self = Self("NonCPULens7FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS7_MAX_APERTURE: Self = Self("NonCPULens7MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS8_FOCAL_LENGTH: Self = Self("NonCPULens8FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS8_MAX_APERTURE: Self = Self("NonCPULens8MaxAperture");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS9_FOCAL_LENGTH: Self = Self("NonCPULens9FocalLength");: Self = Self("");
    pub const pub const NIKON_NON_C_P_U_LENS9_MAX_APERTURE: Self = Self("NonCPULens9MaxAperture");: Self = Self("");
    pub const pub const NIKON_PHOTO_SHOOTING_MENU_BANK_IMAGE_AREA: Self =: Self = Self("");
    pub const pub const NIKON_PREVIEW_IMAGE1: Self = Self("PreviewImage1");: Self = Self("");
    pub const pub const NIKON_PREVIEW_IMAGE2: Self = Self("PreviewImage2");: Self = Self("");
    pub const pub const NIKON_RADIAL_DISTORTION_COEFFICIENT1: Self = Self("RadialDistortionCoefficient1");: Self = Self("");
    pub const pub const NIKON_RADIAL_DISTORTION_COEFFICIENT2: Self = Self("RadialDistortionCoefficient2");: Self = Self("");
    pub const pub const NIKON_RADIAL_DISTORTION_COEFFICIENT3: Self = Self("RadialDistortionCoefficient3");: Self = Self("");
    pub const pub const NIKON_SLOT2_JPG_SIZE: Self = Self("Slot2JpgSize");: Self = Self("");
    pub const pub const NIKON_SUB_COMMAND_DIAL_FRAME_ADVANCE_ZOOM: Self =: Self = Self("");
    pub const pub const NIKON_UNKNOWN_INFO2_VERSION: Self = Self("UnknownInfo2Version");: Self = Self("");
    pub const pub const NIKON_VIEW_MODE_SHOW_EFFECTS_OF_SETTINGS: Self =: Self = Self("");
    pub const pub const NIKON_VIGNETTE_COEFFICIENT1: Self = Self("VignetteCoefficient1");: Self = Self("");
    pub const pub const NIKON_VIGNETTE_COEFFICIENT2: Self = Self("VignetteCoefficient2");: Self = Self("");
    pub const pub const NIKON_VIGNETTE_COEFFICIENT3: Self = Self("VignetteCoefficient3");: Self = Self("");
    pub const pub const SONY_A5: Self = Self("A5");: Self = Self("");
    pub const pub const SONY_A6: Self = Self("A6");: Self = Self("");
    pub const pub const SONY_A7: Self = Self("A7");: Self = Self("");
    pub const pub const SONY_A_F_STATUS_CENTER_F2: Self = Self("AFStatusCenterF2");: Self = Self("");
    pub const pub const SONY_B10: Self = Self("B10");: Self = Self("");
    pub const pub const SONY_B2: Self = Self("B2");: Self = Self("");
    pub const pub const SONY_B3: Self = Self("B3");: Self = Self("");
    pub const pub const SONY_B4: Self = Self("B4");: Self = Self("");
    pub const pub const SONY_B5: Self = Self("B5");: Self = Self("");
    pub const pub const SONY_B6: Self = Self("B6");: Self = Self("");
    pub const pub const SONY_B7: Self = Self("B7");: Self = Self("");
    pub const pub const SONY_B8: Self = Self("B8");: Self = Self("");
    pub const pub const SONY_B9: Self = Self("B9");: Self = Self("");
    pub const pub const SONY_BATTERY_LEVEL2: Self = Self("BatteryLevel2");: Self = Self("");
    pub const pub const SONY_BATTERY_LEVEL_GRIP1: Self = Self("BatteryLevelGrip1");: Self = Self("");
    pub const pub const SONY_BATTERY_LEVEL_GRIP2: Self = Self("BatteryLevelGrip2");: Self = Self("");
    pub const pub const SONY_BATTERY_VOLTAGE1: Self = Self("BatteryVoltage1");: Self = Self("");
    pub const pub const SONY_BATTERY_VOLTAGE2: Self = Self("BatteryVoltage2");: Self = Self("");
    pub const pub const SONY_BRACKET_SHOT_NUMBER2: Self = Self("BracketShotNumber2");: Self = Self("");
    pub const pub const SONY_C1: Self = Self("C1");: Self = Self("");
    pub const pub const SONY_C10: Self = Self("C10");: Self = Self("");
    pub const pub const SONY_C11: Self = Self("C11");: Self = Self("");
    pub const pub const SONY_C2: Self = Self("C2");: Self = Self("");
    pub const pub const SONY_C3: Self = Self("C3");: Self = Self("");
    pub const pub const SONY_C4: Self = Self("C4");: Self = Self("");
    pub const pub const SONY_C5: Self = Self("C5");: Self = Self("");
    pub const pub const SONY_C6: Self = Self("C6");: Self = Self("");
    pub const pub const SONY_C7: Self = Self("C7");: Self = Self("");
    pub const pub const SONY_C8: Self = Self("C8");: Self = Self("");
    pub const pub const SONY_C9: Self = Self("C9");: Self = Self("");
    pub const pub const SONY_D1: Self = Self("D1");: Self = Self("");
    pub const pub const SONY_D10: Self = Self("D10");: Self = Self("");
    pub const pub const SONY_D11: Self = Self("D11");: Self = Self("");
    pub const pub const SONY_D2: Self = Self("D2");: Self = Self("");
    pub const pub const SONY_D3: Self = Self("D3");: Self = Self("");
    pub const pub const SONY_D4: Self = Self("D4");: Self = Self("");
    pub const pub const SONY_D5: Self = Self("D5");: Self = Self("");
    pub const pub const SONY_D6: Self = Self("D6");: Self = Self("");
    pub const pub const SONY_D7: Self = Self("D7");: Self = Self("");
    pub const pub const SONY_D8: Self = Self("D8");: Self = Self("");
    pub const pub const SONY_D9: Self = Self("D9");: Self = Self("");
    pub const pub const SONY_DRIVE_MODE2: Self = Self("DriveMode2");: Self = Self("");
    pub const pub const SONY_E1: Self = Self("E1");: Self = Self("");
    pub const pub const SONY_E10: Self = Self("E10");: Self = Self("");
    pub const pub const SONY_E11: Self = Self("E11");: Self = Self("");
    pub const pub const SONY_E2: Self = Self("E2");: Self = Self("");
    pub const pub const SONY_E3: Self = Self("E3");: Self = Self("");
    pub const pub const SONY_E4: Self = Self("E4");: Self = Self("");
    pub const pub const SONY_E5: Self = Self("E5");: Self = Self("");
    pub const pub const SONY_E6: Self = Self("E6");: Self = Self("");
    pub const pub const SONY_E7: Self = Self("E7");: Self = Self("");
    pub const pub const SONY_E8: Self = Self("E8");: Self = Self("");
    pub const pub const SONY_E9: Self = Self("E9");: Self = Self("");
    pub const pub const SONY_ELECTRICAL_EXTENDER_MAGNIFICATION: Self =: Self = Self("");
    pub const pub const SONY_EXPOSURE_COMPENSATION2: Self = Self("ExposureCompensation2");: Self = Self("");
    pub const pub const SONY_F1: Self = Self("F1");: Self = Self("");
    pub const pub const SONY_F10: Self = Self("F10");: Self = Self("");
    pub const pub const SONY_F11: Self = Self("F11");: Self = Self("");
    pub const pub const SONY_F2: Self = Self("F2");: Self = Self("");
    pub const pub const SONY_F3: Self = Self("F3");: Self = Self("");
    pub const pub const SONY_F4: Self = Self("F4");: Self = Self("");
    pub const pub const SONY_F5: Self = Self("F5");: Self = Self("");
    pub const pub const SONY_F6: Self = Self("F6");: Self = Self("");
    pub const pub const SONY_F7: Self = Self("F7");: Self = Self("");
    pub const pub const SONY_F8: Self = Self("F8");: Self = Self("");
    pub const pub const SONY_F9: Self = Self("F9");: Self = Self("");
    pub const pub const SONY_FACE1_POSITION: Self = Self("Face1Position");: Self = Self("");
    pub const pub const SONY_FACE2_POSITION: Self = Self("Face2Position");: Self = Self("");
    pub const pub const SONY_FACE3_POSITION: Self = Self("Face3Position");: Self = Self("");
    pub const pub const SONY_FACE4_POSITION: Self = Self("Face4Position");: Self = Self("");
    pub const pub const SONY_FACE5_POSITION: Self = Self("Face5Position");: Self = Self("");
    pub const pub const SONY_FACE6_POSITION: Self = Self("Face6Position");: Self = Self("");
    pub const pub const SONY_FACE7_POSITION: Self = Self("Face7Position");: Self = Self("");
    pub const pub const SONY_FACE8_POSITION: Self = Self("Face8Position");: Self = Self("");
    pub const pub const SONY_FLASH_ACTION2: Self = Self("FlashAction2");: Self = Self("");
    pub const pub const SONY_FLASH_EXPOSURE_COMP_SET2: Self = Self("FlashExposureCompSet2");: Self = Self("");
    pub const pub const SONY_FOCAL_LENGTH2: Self = Self("FocalLength2");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION1: Self = Self("FocalPlaneAFPointLocation1");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION10: Self = Self("FocalPlaneAFPointLocation10");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION11: Self = Self("FocalPlaneAFPointLocation11");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION12: Self = Self("FocalPlaneAFPointLocation12");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION13: Self = Self("FocalPlaneAFPointLocation13");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION14: Self = Self("FocalPlaneAFPointLocation14");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION15: Self = Self("FocalPlaneAFPointLocation15");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION2: Self = Self("FocalPlaneAFPointLocation2");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION3: Self = Self("FocalPlaneAFPointLocation3");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION4: Self = Self("FocalPlaneAFPointLocation4");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION5: Self = Self("FocalPlaneAFPointLocation5");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION6: Self = Self("FocalPlaneAFPointLocation6");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION7: Self = Self("FocalPlaneAFPointLocation7");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION8: Self = Self("FocalPlaneAFPointLocation8");: Self = Self("");
    pub const pub const SONY_FOCAL_PLANE_A_F_POINT_LOCATION9: Self = Self("FocalPlaneAFPointLocation9");: Self = Self("");
    pub const pub const SONY_FOCUS_LOCATION2: Self = Self("FocusLocation2");: Self = Self("");
    pub const pub const SONY_FOCUS_MODE2: Self = Self("FocusMode2");: Self = Self("");
    pub const pub const SONY_FOCUS_POSITION2: Self = Self("FocusPosition2");: Self = Self("");
    pub const pub const SONY_G1: Self = Self("G1");: Self = Self("");
    pub const pub const SONY_G10: Self = Self("G10");: Self = Self("");
    pub const pub const SONY_G11: Self = Self("G11");: Self = Self("");
    pub const pub const SONY_G2: Self = Self("G2");: Self = Self("");
    pub const pub const SONY_G3: Self = Self("G3");: Self = Self("");
    pub const pub const SONY_G4: Self = Self("G4");: Self = Self("");
    pub const pub const SONY_G5: Self = Self("G5");: Self = Self("");
    pub const pub const SONY_G6: Self = Self("G6");: Self = Self("");
    pub const pub const SONY_G7: Self = Self("G7");: Self = Self("");
    pub const pub const SONY_G8: Self = Self("G8");: Self = Self("");
    pub const pub const SONY_G9: Self = Self("G9");: Self = Self("");
    pub const pub const SONY_H10: Self = Self("H10");: Self = Self("");
    pub const pub const SONY_H2: Self = Self("H2");: Self = Self("");
    pub const pub const SONY_H3: Self = Self("H3");: Self = Self("");
    pub const pub const SONY_H4: Self = Self("H4");: Self = Self("");
    pub const pub const SONY_H5: Self = Self("H5");: Self = Self("");
    pub const pub const SONY_H6: Self = Self("H6");: Self = Self("");
    pub const pub const SONY_H7: Self = Self("H7");: Self = Self("");
    pub const pub const SONY_H8: Self = Self("H8");: Self = Self("");
    pub const pub const SONY_H9: Self = Self("H9");: Self = Self("");
    pub const pub const SONY_HIGH_I_S_O_NOISE_REDUCTION2: Self = Self("HighISONoiseReduction2");: Self = Self("");
    pub const pub const SONY_I5: Self = Self("I5");: Self = Self("");
    pub const pub const SONY_I6: Self = Self("I6");: Self = Self("");
    pub const pub const SONY_I7: Self = Self("I7");: Self = Self("");
    pub const pub const SONY_IMAGE_STABILIZATION2: Self = Self("ImageStabilization2");: Self = Self("");
    pub const pub const SONY_LENS_MOUNT2: Self = Self("LensMount2");: Self = Self("");
    pub const pub const SONY_LENS_TYPE2: Self = Self("LensType2");: Self = Self("");
    pub const pub const SONY_LENS_TYPE3: Self = Self("LensType3");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW1: Self = Self("MeterInfo1Row1");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW2: Self = Self("MeterInfo1Row2");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW3: Self = Self("MeterInfo1Row3");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW4: Self = Self("MeterInfo1Row4");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW5: Self = Self("MeterInfo1Row5");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW6: Self = Self("MeterInfo1Row6");: Self = Self("");
    pub const pub const SONY_METER_INFO1_ROW7: Self = Self("MeterInfo1Row7");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW1: Self = Self("MeterInfo2Row1");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW2: Self = Self("MeterInfo2Row2");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW3: Self = Self("MeterInfo2Row3");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW4: Self = Self("MeterInfo2Row4");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW5: Self = Self("MeterInfo2Row5");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW6: Self = Self("MeterInfo2Row6");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW7: Self = Self("MeterInfo2Row7");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW8: Self = Self("MeterInfo2Row8");: Self = Self("");
    pub const pub const SONY_METER_INFO2_ROW9: Self = Self("MeterInfo2Row9");: Self = Self("");
    pub const pub const SONY_METERING_MODE2: Self = Self("MeteringMode2");: Self = Self("");
    pub const pub const SONY_ORIENTATION2: Self = Self("Orientation2");: Self = Self("");
    pub const pub const SONY_PANORAMA_SIZE3_D: Self = Self("PanoramaSize3D");: Self = Self("");
    pub const pub const SONY_PICTURE_EFFECT2: Self = Self("PictureEffect2");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE1_POSITION: Self = Self("PotentialFace1Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE2_POSITION: Self = Self("PotentialFace2Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE3_POSITION: Self = Self("PotentialFace3Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE4_POSITION: Self = Self("PotentialFace4Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE5_POSITION: Self = Self("PotentialFace5Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE6_POSITION: Self = Self("PotentialFace6Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE7_POSITION: Self = Self("PotentialFace7Position");: Self = Self("");
    pub const pub const SONY_POTENTIAL_FACE8_POSITION: Self = Self("PotentialFace8Position");: Self = Self("");
    pub const pub const SONY_QUALITY2: Self = Self("Quality2");: Self = Self("");
    pub const pub const SONY_RELEASE_MODE2: Self = Self("ReleaseMode2");: Self = Self("");
    pub const pub const SONY_RELEASE_MODE3: Self = Self("ReleaseMode3");: Self = Self("");
    pub const pub const SONY_SHOT_NUMBER_SINCE_POWER_UP2: Self = Self("ShotNumberSincePowerUp2");: Self = Self("");
    pub const pub const SONY_SHUTTER_COUNT2: Self = Self("ShutterCount2");: Self = Self("");
    pub const pub const SONY_SHUTTER_COUNT3: Self = Self("ShutterCount3");: Self = Self("");
    pub const pub const SONY_SONY_DATE_TIME2: Self = Self("SonyDateTime2");: Self = Self("");
    pub const pub const SONY_SONY_EXPOSURE_TIME2: Self = Self("SonyExposureTime2");: Self = Self("");
    pub const pub const SONY_SONY_F_NUMBER2: Self = Self("SonyFNumber2");: Self = Self("");
    pub const pub const SONY_TEXT_INFO1: Self = Self("TextInfo1");: Self = Self("");
    pub const pub const SONY_TEXT_INFO2: Self = Self("TextInfo2");: Self = Self("");
    pub const pub const SONY_VIEWING_MODE2: Self = Self("ViewingMode2");: Self = Self("");
    pub const pub const FUJI_HIGH_IS0_NOISE_REDUCTION: Self = Self("FujiHighIS0NoiseReduction");: Self = Self("");
    pub const pub const PANASONIC_IMAGE_STABILIZATION2: Self = Self("PanasonicImageStabilization2");: Self = Self("");
    pub const PENTAX_MODEL_TYPE: Self = Self("PentaxModelType");
    pub const PENTAX_IMAGE_SIZE: Self = Self("PentaxImageSize");
    pub const PENTAX_QUALITY: Self = Self("PentaxQuality");
    pub const PENTAX_IMAGE_PROCESSING: Self = Self("PentaxImageProcessing");
    pub const PENTAX_FOCUS_MODE: Self = Self("PentaxFocusMode");
    pub const PENTAX_AF_POINT: Self = Self("PentaxAFPoint");
    pub const PENTAX_AUTO_BRACKETING: Self = Self("PentaxAutoBracketing");
    pub const PENTAX_WHITE_BALANCE: Self = Self("PentaxWhiteBalance");
    pub const DURATION: Self = Self("Duration");
    pub const VIDEO_FRAME_RATE: Self = Self("VideoFrameRate");
    pub const VIDEO_FRAME_COUNT: Self = Self("VideoFrameCount");
    pub const VIDEO_BIT_RATE: Self = Self("VideoBitRate");
    pub const AUDIO_BIT_RATE: Self = Self("AudioBitRate");
    pub const VIDEO_COMPRESSION: Self = Self("VideoCompression");
    pub const AUDIO_COMPRESSION: Self = Self("AudioCompression");
    pub const TRACK_NUMBER: Self = Self("TrackNumber");
    pub const TRACK_TYPE: Self = Self("TrackType");
    pub const TRACK_CREATE_DATE: Self = Self("TrackCreateDate");
    pub const TRACK_MODIFY_DATE: Self = Self("TrackModifyDate");
    pub const MEDIA_CREATE_DATE: Self = Self("MediaCreateDate");
    pub const MEDIA_MODIFY_DATE: Self = Self("MediaModifyDate");
    pub const MEDIA_DATA_SIZE: Self = Self("MediaDataSize");
    pub const MEDIA_DATA_OFFSET: Self = Self("MediaDataOffset");
    pub const GENRE: Self = Self("Genre");
    pub const ALBUM: Self = Self("Album");
    pub const YEAR: Self = Self("Year");
    pub const COMMENT: Self = Self("Comment");
    pub const LYRICS: Self = Self("Lyrics");
    pub const COMPOSER: Self = Self("Composer");
    pub const PUBLISHER: Self = Self("Publisher");
    pub const FILE_DESCRIPTION: Self = Self("FileDescription");
    pub const FILE_VERSION: Self = Self("FileVersion");
    pub const INTERNAL_VERSION_NUMBER: Self = Self("InternalVersionNumber");
    pub const COMPANY_NAME: Self = Self("CompanyName");
    pub const LEGAL_COPYRIGHT: Self = Self("LegalCopyright");
    pub const PRODUCT_NAME: Self = Self("ProductName");
    pub const PRODUCT_VERSION: Self = Self("ProductVersion");
    pub const MIME_ENCODING: Self = Self("MIMEEncoding");
    pub const pub const NIKON_SERIAL_NUMBER_2_EXT: Self = Self("NikonSerialNumber2");: Self = Self("");
    pub const pub const NIKON_SHUTTER_COUNT_2_EXT: Self = Self("NikonShutterCount2");: Self = Self("");
    pub const pub const NIKON_FLASH_MODE_2_EXT: Self = Self("NikonFlashMode2");: Self = Self("");
    pub const pub const NIKON_FLASH_EXPOSURE_COMP_2_EXT: Self = Self("NikonFlashExposureComp2");: Self = Self("");
    pub const pub const SONY_CHROMATIC_ABERRATION_CORRECTION_EXT: Self =: Self = Self("");
    pub const VIDEO_TRACK_CREATE_DATE_EXT: Self = Self("TrackCreateDate");
    pub const VIDEO_TRACK_MODIFY_DATE_EXT: Self = Self("TrackModifyDate");
    pub const VIDEO_MEDIA_CREATE_DATE_EXT: Self = Self("MediaCreateDate");
    pub const VIDEO_MEDIA_MODIFY_DATE_EXT: Self = Self("MediaModifyDate");
    pub const VIDEO_HANDLER_TYPE_EXT: Self = Self("HandlerType");
    pub const VIDEO_HANDLER_DESCRIPTION_EXT: Self = Self("HandlerDescription");
    pub const VIDEO_COMPRESSOR_ID_EXT: Self = Self("CompressorID");
    pub const VIDEO_BITS_PER_COMPONENT_EXT: Self = Self("BitsPerComponent");
    pub const VIDEO_COLOR_PROFILE_EXT: Self = Self("VideoColorProfile");
    pub const VIDEO_AUDIO_FORMAT_EXT: Self = Self("AudioFormat");
    pub const VIDEO_AUDIO_CHANNELS_EXT: Self = Self("AudioChannels");
    pub const VIDEO_AUDIO_BITS_PER_SAMPLE_EXT: Self = Self("AudioBitsPerSample");
    pub const VIDEO_AUDIO_SAMPLE_RATE_EXT: Self = Self("AudioSampleRate");
    pub const VIDEO_DURATION_EXT: Self = Self("Duration");
    pub const VIDEO_MOVIE_HEADER_VERSION_EXT: Self = Self("MovieHeaderVersion");
    pub const VIDEO_TIME_SCALE_EXT: Self = Self("TimeScale");
    pub const VIDEO_PREFERRED_RATE_EXT: Self = Self("PreferredRate");
    pub const VIDEO_PREFERRED_VOLUME_EXT: Self = Self("PreferredVolume");
    pub const VIDEO_PREVIEW_TIME_EXT: Self = Self("PreviewTime");
    pub const VIDEO_PREVIEW_DURATION_EXT: Self = Self("PreviewDuration");
    pub const VIDEO_POSTER_TIME_EXT: Self = Self("PosterTime");
    pub const VIDEO_SELECTION_TIME_EXT: Self = Self("SelectionTime");
    pub const VIDEO_SELECTION_DURATION_EXT: Self = Self("SelectionDuration");
    pub const VIDEO_CURRENT_TIME_EXT: Self = Self("CurrentTime");
    pub const VIDEO_NEXT_TRACK_ID_EXT: Self = Self("NextTrackID");
    pub const VIDEO_TRACK_ID_EXT: Self = Self("VideoTrackID");
    pub const VIDEO_TRACK_LAYER_EXT: Self = Self("VideoTrackLayer");
    pub const VIDEO_TRACK_VOLUME_EXT: Self = Self("VideoTrackVolume");
    pub const VIDEO_TRACK_DURATION_EXT: Self = Self("VideoTrackDuration");
    pub const VIDEO_WIDTH_EXT: Self = Self("VideoWidth");
    pub const DNG_VERSION_EXT: Self = Self("DNGVersion");
    pub const DNG_BACKWARD_VERSION_EXT: Self = Self("DNGBackwardVersion");
    pub const UNIQUE_CAMERA_MODEL_EXT: Self = Self("UniqueCameraModel");
    pub const LOCALIZED_CAMERA_MODEL_EXT: Self = Self("LocalizedCameraModel");
    pub const CFA_PLANE_COLOR_EXT: Self = Self("CFAPlaneColor");
    pub const CFA_LAYOUT_EXT: Self = Self("CFALayout");
    pub const LINEARIZATION_TABLE_EXT: Self = Self("LinearizationTable");
    pub const BLACK_LEVEL_EXT: Self = Self("BlackLevel");
    pub const WHITE_LEVEL_EXT: Self = Self("WhiteLevel");
    pub const DEFAULT_SCALE_EXT: Self = Self("DefaultScale");
    pub const BEST_QUALITY_SCALE_EXT: Self = Self("BestQualityScale");
    pub const DEFAULT_CROP_ORIGIN_EXT: Self = Self("DefaultCropOrigin");
    pub const DEFAULT_CROP_SIZE_EXT: Self = Self("DefaultCropSize");
    pub const pub const CALIBRATION_ILLUMINANT_1_EXT: Self = Self("CalibrationIlluminant1");: Self = Self("");
    pub const pub const CALIBRATION_ILLUMINANT_2_EXT: Self = Self("CalibrationIlluminant2");: Self = Self("");
    pub const pub const COLOR_MATRIX_1_EXT: Self = Self("ColorMatrix1");: Self = Self("");
    pub const pub const COLOR_MATRIX_2_EXT: Self = Self("ColorMatrix2");: Self = Self("");
    pub const pub const CAMERA_CALIBRATION_1_EXT: Self = Self("CameraCalibration1");: Self = Self("");
    pub const pub const CAMERA_CALIBRATION_2_EXT: Self = Self("CameraCalibration2");: Self = Self("");
    pub const ANALOG_BALANCE_EXT: Self = Self("AnalogBalance");
}
